print('Anna paino')
leivis = float(input('Leiviskät: '))
naula = float(input('Naulat: '))
luoti = float(input('Luodit: '))
paino = 13.3 * ((leivis * 20 + naula) * 32 + luoti)
print('Paino nykymittojen mukaan on: \n' + str(int(paino / 1000)) + ' kiloa ja ' + str(round(paino % 1000, 2)) + ' grammaa')